### PR TITLE
Adds support for running and debugging the solution in Docker Compose

### PR DESCRIPTION
**Pull request by JamesDawson**
Implements an additional hosting option for running this sample using Docker Compose.

Also adds a Visual Studio solution that utilises the 'Container development tools' feature to provide a low friction method for debugging the distributed application when hosted in Docker Compose.

The only code change relates to enabling the FineCollectionService to understand whether it is running on Kubernetes or just as a simple container, to ensure the correct secrets logic is used.

### CODE REVIEW

**Comment by EdwinVW** [comment]
Hi @JamesDawson, Thanks for your PR! 

Because this sample is used for the book Dapr for .NET developers I co-authored, I will discuss with the other authors to decide whether we want to merge the PR to add this to the sample app. We do not want to confuse people with too many different ways of running the application (we now support self-hosted and Kubernetes). I'll let you know a.s.a.p. when we have a conclusion. 

Meanwhile, I was testing the application with docker-compose and I ran into the issue that the ports used by Zipkin and Redis were already in use:

```
ERROR: for dtc-zipkin  Cannot start service dtc-zipkin: driver failed programming external connectivity on endpoint src_dtc-zipkin_1 (bf06ac9193b21079399f82f56a1a9a50eeae31c7f6b1e087443b8362c7eadc1d): Bind for 0.0.0.0:9411 failed: port is already allocated
ERROR: for dtc-redis  Cannot start service dtc-redis: driver failed programming external connectivity on endpoint src_dtc-redis_1 (9d2b324cd3997977ebea527679bd5a5aec124ea7d621cb71d18e39cec52e6871): Bind for 0.0.0.0:6379 failed: port is already allocated
```

I have Dapr already installed on my machine, so it makes sense that those ports are in use. This should not be an issue. So I've changed the port-numbers for Zipkin and Redis (both in the docker-compose as in the config files) to `19411` and `16379` respectively, and that fixes the problem.

Also I miss the console-based simulator. I would like that to be the default simulator (again to keep it simple for the users) and use the VisualSimulation as an extra bonus.

**Comment by HowardvanRooijen** [comment]
Hi Edwin,

A little bit of context - I'm actually working my way through your Dapr for .NET Developers book (and enjoying it very much!). @JamesDawson & I collaborated on making these changes, because we found it made the solution much easier to demo to our internal engineering teams during one of our weekly "show & tell" sessions. It enabled us to set breakpoints / jump between the different projects and show "the flow", and contextualised a whole "new world" inside an environment they are already very familiar with. It also meant they could pull the repo, open it in VS and have an F5 debug experience.

**Comment by JamesDawson** [comment]
Hi @EdwinVW, thanks for taking a look at the PR - I've pushed up a couple of changes as per your feedback.

**Comment by HowardvanRooijen** [comment]
Now that the announcement is public - the reason we did the above is that we were trying to get the example to run on Azure Container Apps. I'm not sure if you've tried this yet? We'd be happy to collaborate.

**Comment by EdwinVW** [comment]
Hi @JamesDawson and @HowardvanRooijen. I've discussed this PR with the co-authors of the Dapr book and we've decided not to merge it into this repo. I hope you understand. Feel free to use it for demos though in your own fork of the repo.

Thanks again for the PR and your interest in the Dapr Traffic Control sample! FYI: I will be updating the sample code to .NET 6 and C# 10 soon (along with the Dapr book). So expect quite some changes in the code-base.

**Pull request closed without merging**
